name: Generate PDF and Presentation

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.2

    - name: Install Nix
      uses: cachix/install-nix-action@v20

    - name: Build main PDF and Presentation
      run: |
        NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/22.11.tar.gz nix-shell --run "make || true"
        NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/22.11.tar.gz nix-shell --run "make || true"
        NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/22.11.tar.gz nix-shell --run "make presentation || true"
        NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/22.11.tar.gz nix-shell --run "make presentation || true"

    - name: Upload main artifact
      if: always()
      uses: actions/upload-artifact@v3.1.2
      with:
        path: main.pdf

    - name: Upload presentation artifact
      if: always()
      uses: actions/upload-artifact@v3.1.2
      with:
        path: presentation.pdf
