name: Generate PDF

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.7.0

    - name: Install Nix
      uses: cachix/install-nix-action@v20

    - name: Clone dotfiles
      run: git clone https://github.com/siraben/dotfiles.git

    - name: Symlink Emacs configuration
      run: ln -s $PWD/dotfiles/emacs/.emacs.d $HOME/.emacs.d

    - name: Build PDF
      run: |
        NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/22.11.tar.gz nix-shell --run "make"
